Re-run configuration if no peer handshake  or if > 3mins old

diff --git a/app/wg/run b/app/wg/run
--- a/app/wg/run
+++ b/app/wg/run
@@ -4,7 +4,12 @@ set -e -u -o pipefail
 [[ "$VPN_PROTOCOL" != "wireguard" ]] && exit 0
 
 if [[ -f "/app/wg/token" ]]; then
-  sleep 900
+  # Check if peer connected
+  hs=$(wg | sed -nr 's/latest handshake: ((([0-9]+ minute[s]?), )?([0-9]+ second[s]?)) ago/\3 \4/p')
+  [[ -n "$hs" ]] && exit 0
+  d=$(date -ud "1970-01-01 00:00:00 UTC $hs" "+%s")
+  # Check latest handshake is < 3 mins ago
+  [[ "$d" -le "300" ]] && exit 0
 fi
 
 echo "Removing existing token..."
@@ -54,7 +59,7 @@ wireguard_json="$(curl -s -G \
 
 # Check if the API returned OK and stop this script if it didn't.
 if [[ $(echo "$wireguard_json" | jq -r '.status') != "OK" ]]; then
-  >&2 echo "Server did not return OK. Stopping now."
+  >&2 echo "ERROR: Server did not return OK."
   exit 1
 fi
 
@@ -74,9 +79,12 @@ PublicKey = $(echo "$wireguard_json" | jq -r '.server_key')
 AllowedIPs = 0.0.0.0/0
 Endpoint = ${WG_SERVER_IP}:$(echo "$wireguard_json" | jq -r '.server_port')
 EOF
+echo
 
-echo "Disabling existing connections..."
-wg-quick down pia && echo "done"
+if [[ "$(wg | grep -cm1 'interface: pia')" -eq "1" ]]; then
+  echo "Disabling existing connections..."
+  wg-quick down pia && echo "done"
+fi
 
 # Start the WireGuard interface.
 #
