Updated messages

diff --git a/app/ovpn/run b/app/ovpn/run
--- a/app/ovpn/run
+++ b/app/ovpn/run
@@ -6,7 +6,7 @@ PIA_OVPN_CONFIG_URL='https://www.privateinternetaccess.com/openvpn/openvpn-stron
 
 [ ! -d /app/ovpn/config ] && mkdir -p /app/ovpn/config
 # download and install the latest default recommended ovpn configs
-wget -q $PIA_OVPN_CONFIG_URL -O pia_ovpn_configs.zip || (echo "ERROR: Failed to download PIA configuration files, exitting" && exit 1)
+wget -q $PIA_OVPN_CONFIG_URL -O pia_ovpn_configs.zip || (echo "ERROR: Failed to download PIA configuration files, exiting" && exit 1)
 unzip -uoq pia_ovpn_configs.zip -d /app/ovpn/config
 rm -f pia_ovpn_configs.zip
 
@@ -21,7 +21,7 @@ fi
 if [ -n "$REGION" ]; then
   REGION=$(echo $REGION | sed 's/ /_/g' | tr '[:upper:]' '[:lower:]')
   if [[ ! -f "/config/pia/${REGION}.ovpn" ]]; then
-    echo "ERROR: OpenVPN configuration profile not found, check your REGION environment variable, see https://www.privateinternetaccess.com/pages/network/dkrpia for possible choices" 
+    echo "ERROR: OpenVPN configuration profile not found, check your REGION environment variable, see the OpenVPN generator in the client control panel for possible choices"
     exit 1
   fi
   set -- "$@" '--config' "/config/pia/${REGION}.ovpn"
